# The URL the site will be built for
base_url = "https://www.baemazhen.com"

title = "baemazhen"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

theme = "after-dark"

paginate_by = 5

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]


[extra]

author = "baemazhen"

after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"}
]

after_dark_title = "baemazhen"